
clusters:
  - name: aws-iam-authenticator
    cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lRUHJ1cnRvSXJWZkI1T1hIMlNEN3phakFOQmdrcWhraUc5dzBCQVFzRkFEQWcKTVI0d0hBWURWUVFERXhWaGQzTXRhV0Z0TFdGMWRHaGxiblJwWTJGMGIzSXdJQmNOTWpRd056RXlNREV4TkRNMgpXaGdQTWpFeU5EQTJNVGd3TVRFME16WmFNQ0F4SGpBY0JnTlZCQU1URldGM2N5MXBZVzB0WVhWMGFHVnVkR2xqCllYUnZjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFOS0NLeWZteUpSb1RzUEoKUEVGS1lyajJURTZaY2xsN1NPM1o5UDU5aFhiQVRVQVJCMWZxVDhKTjJ6cXRvd2IyWHZVZ0kxVCtrRFcwa0tsUQpYaHhNWTRMMDJldUR1RitUblR2SmdQZGcvZlBVWndXZWNPQ3R1b2FmdHg2M3RDU3pPQ2NYYTd5NUh5ZXdhQ2J6CjB2TU5Wb0Z1QkYrSGNxaVZ2YU9iRDVqeGMwU05KUVdySW43elFkT3g1clRiK1lPMk9JVUdCejZJYjEvSnhnUDMKYnhvSHJBMHR0akhZYkxxU2hZUDR3OElmNWdvOEtUTG02TFVqcDVHOS9wZGhXL3NjNWd0RTBlbDJEb2Vyb2kvdQowS1NESHhZQXJlK1p1ZmptMFUxYngvTVpEVklQQkwxWGN5a1J3NkVKS0dLYldQVGluUmRNbVUyWXQ0R2ZHbmRRClBFQ1VGek1DQXdFQUFhTnpNSEV3RGdZRFZSMFBBUUgvQkFRREFnS2tNQk1HQTFVZEpRUU1NQW9HQ0NzR0FRVUYKQndNQk1BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZLSUlKZ2ZLVk1xc0pZanlFc1l3WkdEWAoxZ3lHTUJvR0ExVWRFUVFUTUJHQ0NXeHZZMkZzYUc5emRJY0Vmd0FBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFSSS9vUlExcWxHcHZnV1JEQnozSEl3cXVWWVJyb3BNZ04wSzhjUzVrWTd6ckx3MndSRjl0STlGd0UyM2gKVWJocnlCVVJrYmRvUVRPeG85NSsxV2haYlBXcUVZZm1LamZkRTVNY2hPNnZyTjI5cjFEQ2dyY1FydXZmUXpZTwp6dEV6dVo2RUExZG00U1E3VHBpVnJyZEgyUWlUY2hHemhmN3RVOUFHaEZuNUxPYmRuWExNT3AzWUtDeFFxWEJUCkc2V1ZoY2FsR08ycWNSWmpkNzFsWXZhc0JzbWZZcEFicHhKWU5UREx6RUdwc3poaDE0bEV0dlI0WmRwYklzSG4KaGU0UUo4bWJPclhHcVA2Tk1IMDZrS1lPVmFTSFRiZEQ2RGlZMUFueHlBZE13VE1OOThZV0l2TlFoNlk1ckhJbQp4cGNrdUNhKzY4YkYwTFVGcHJBMDZpMzJtZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://localhost:21362/authenticate
# user refers to the API server client
users:
  - name: apiserver
current-context: webhook
contexts:
- name: webhook
  context:
    cluster: aws-iam-authenticator
    user: apiserver
